lib/simplecov-html.rb
As soon as binary mode is the same as text mode in unixes, there is no need to detect OS/platform.
This also fixes output of non-ascii characters met in sources.
=> always use binary file format

lib/simplecov-html.rb
Fixed a issue of Rubocop.
```
.....C..
Offenses:
lib/simplecov-html.rb:8:22: C: Unnecessary spacing detected.
major, minor, patch =  SimpleCov::VERSION.scan(/\d+/).first(3).map(&:to_i)
^
8 files inspected, 1 offense detected
```
```
Inspecting 8 files
........
8 files inspected, no offenses detected
```
=> Fix a issue of rubocop

lib/simplecov-html.rb
Uses `sub` instead of `gsub` to avoid replacing file paths that include the root, such as the "app" in "application" when the root directory is `/app`.
I noticed this occurring when developing Rails apps within Docker. A codebase mounted at `/app` would cause `application_helper.rb` to be cut to `../helpers.lication_helper.rb` as the original path is `/app/app/helpers/application_helper.rb`. Not a major issue, just looks very odd in the generated coverage report.
Basic example of issue: https://gist.github.com/akamike/393bede2b89645b946c8d95ac4f5bcf9 and screenshot of greedy replace in action (from the app I first noticed this on):
=> Fix greedy shortened_filename replace

views/source_file.erb
The behavior of `Enumerable#each_with_index` has changed in JRuby 9.1.9.0.
jruby/jruby#4610
This PR used `each` method because it do not use a block variable of index.
The purpose of this change is to fix the following error at simplecov.
colszowka/simplecov#582
Thanks.
=> Use `each` instead of `each_with_index` in source_file.erb

lib/simplecov-html/version.rb
This change ensures that all string literals can be frozen (as per the optional feature in MRI 2.3 and onwards). I would recommend adding the following to your `.travis.yml` file to ensure regressions aren't introduced:
```yml
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
```
This will add the flag when the tests are run on MRI 2.4 or newer (while the feature was introduced in 2.3, it doesn't seem to work reliably until 2.4).
=> Allow library to be used with frozen-string-literals enabled.

lib/simplecov-html.rb
Gives a meaningful message and allows the report to be generated when a file has a non ASCII character. See #439 (https://github.com/colszowka/simplecov/issues/439)
=> Rescue encoding error

.rubocop.yml
Failed for me on GitLab CI
https://github.com/bbatsov/rubocop/blob/v0.53.0/CHANGELOG.md
https://github.com/bbatsov/rubocop/issues/3394
https://github.com/bbatsov/rubocop/pull/5307/files#diff-e93280b3b31a6438c533a5f3232340d8
=> TrailingCommaInLiteral was split in rubocop  0.53.0

.rubocop.yml, .travis.yml, Gemfile, assets/javascripts/application.js, assets/stylesheets/screen.css.sass, lib/simplecov-html.rb, public/application.css, public/application.js, views/file_list.erb, views/source_file.erb
Show statistics of branch coverage result.
You can put this merge on pending until they [merge](https://github.com/colszowka/simplecov/pull/692) `simplecov` gem branch that generates needed statistics. Anyway, these modifications are not harmful.
=> Add ability to support branch coverage statistics ruby >= 2.5

lib/simplecov-html.rb
We make the check sooooo many times that I feel better having
it cached especially when it doesn't make the code more complex
and when it also is unlikely to change while the formatter
is running (read: it shouldn't change then)
=> Cache whether SimpleCov has/had branch coverage enabled

views/source_file.erb
`concat': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
replaces #45
=> Fix UTF8 encoding error

assets/stylesheets/screen.css.sass, public/application.css, views/file_list.erb
Because 2.0.round(2) #=> 2.0, we get better alignment forcing 2 digits after
the decimal point.
Replaces #25
=> Add CSS .number to right-align numeric values.

assets/javascripts/application.js, public/application.js
This PR fixes the off-screen scrolling with a long file-list-container and a short sourcecode-colorbox.
The effect was that, once one is finished scrolling in the colorbox, the scroll would go past the box, and continue to scroll into a big black area, which was supposed to be the file-list-container (but it is black because of the colorbox).
Basically once the colorbox is displayed, the all file-list-container are hidden, and redisplayed after the colorbox is closed. This eliminates the black area underneath the colorbox and eliminates the off-screen-scrolling bug.
=> fix showing/hiding of elements for colorbox

Gemfile.lock, views/source_file.erb
This reverts commit 2608b9d.
Replaced by: colszowka/simplecov#866
As suggested by: #91 (comment)
Should be safe to revert as apparently ruby itself doesn't work
when the encoding isn't declared properly so should be good.
For files that aren't required by ruby but tracked we added a
test case with broken encoding (in simplecov main) but it still
seems to work.  So this complexity is likely not needed anymore.
=> Revert encoding replace

simplecov-html.gemspec
Ruby master branch recently bumped the version number to 3.0: https://github.com/ruby/ruby/commit/21c62fb670b1646c5051a46d29081523cd782f11
This is breaking our ruby-head CI.
=> Update ruby_version requirement to allow ruby 3.0

lib/simplecov-html.rb, views/source_file.erb
See https://github.com/simplecov-ruby/simplecov/pull/1002 for the description.
=> Cache erb templates when generating report

lib/simplecov-html.rb
Almost everyone using branch coverage is going to want to see the
branch coverage and the line coverage output.
=> Print branch coverage with line coverage

lib/simplecov-html.rb
This allows simplecov to generate a single `index.html` file and not have to generate an assets folder if the env var `SIMPLECOV_INLINE_ASSETS` is defined
Resolves https://github.com/simplecov-ruby/simplecov-html/issues/33
Based on the implementation by @eins78 https://github.com/eins78/simplecov-html/commit/939548dabd76d626565ff25f53eda21dd0f8417a
=> [feature] Add inline assets option

lib/simplecov-html.rb
This reverts commit 1ec2e3ba72046f7d1fa5288f726aba75535cb826.
I don't remember why I thought this self-assignment is omittable, but the fact is that Ruby actually warns without this...
=> Bring back self-assignment to suppress Ruby warning

.rubocop.yml
Since our CI fails now due to this silly rule 🤷
=> Let's disable Metrics/ClassLength cop

simplecov-html.gemspec
Gem package size of this gem is significantly becoming larger in recent versions.
```
simplecov-html-0.11.0: 744K
simplecov-html-0.12.0: 1.3M
simplecov-html-0.12.3: 1.3M
```
This seems to be caused via 0eccc9ceacc1d97989c62bcf5fda5836e8315e14 which adds a new js library and starts bundling non-minified version of jQuery. That commit at the same time introduces assets compression, and hence that change didn't really impact the actual runtime performance, but resulted in gem package size growth.
However, since asset files under `assets` directory are used only during precompilation phase and not referenced in users' side, the whole directory can be safely omitted from the gem package.
This patch removes some "development only" files including the `assets` directory. Result of the installed …
=> Reduce gem package size by excluding assets directory

simplecov-html.gemspec
This is raising a critical error in AWS Inspector for any Docker images we create which includes this Gem.
=> Exclude `Gemfile.lock` from Gem

.github/workflows/main.yml, .rubocop.yml, Gemfile, Gemfile.lock, simplecov-html.gemspec
Here's a similar kind of maintenance work with https://github.com/simplecov-ruby/simplecov/pull/1108
Now the CI is running healtily again on all supported Ruby versions of the latest gem release (2.4+).
=> Bring Ruby 2.4+ support back

lib/simplecov-html.rb
by running `FileUtils#cp_r` with the `:remove_destination` option enabled.  This makes asset copying more robust in the face of restrictive permissions on asset file destination paths.  This should be safe and backward-compatible given that the destination files (or their contents) will be fully replaced anyway.
Example case:
```
irb(main):001:0> FileUtils.touch('foo')
=> ["foo"]
irb(main):002:0> FileUtils.touch('bar')
=> ["bar"]
irb(main):003:0> FileUtils.chmod(0o444, 'bar')
=> ["bar"]
irb(main):004:0> FileUtils.cp_r('foo', 'bar')
Errno::EACCES: Permission denied @ rb_sysopen - bar from /nix/store/2kw126cy93rix4pmh9lcl120njnb6r7r-ruby-3.1.4/lib/ruby/3.1.0/fileutils.rb:1395:in `initialize' 
irb(main):005:0> FileUtils.cp_r('foo', 'bar', remove_destination: true) 
=> nil
```
Addresses …
=> Avoid "permission denied" errors copying assets

lib/simplecov-html.rb
- Put percentage first and then covered and total counts in brackets afterwards. Percentage is most critical at a quick glance.
- Put line and brnach coverage on separate lines.
```bash
Coverage report generated for (1/10), (10/10), (2/10), (3/10), (4/10), (5/10), (6/10), (7/10), (8/10), (9/10) to /Users/me/Development/cntral/coverage. 8534 / 16083 LOC (53.06%) covered. 2225 / 4749 branches (46.85%) covered.
```
Now it shows in a clean format, including covered branches, total branches and percent of covered branches. Something like this:
```
Coverage report generated for (1/10), (10/10), (2/10), (3/10), (4/10), (5/10), (6/10), (7/10), (8/10), (9/10) to /Users/me/Development/cntral/coverage.
Line Coverage: 53.06% (8534 / 16083)
Branch Coverage: 46.85% (2225 / 4749)
```
When branch …
=> Improve clarity of line and branch coverage format.

Gemfile, Gemfile.lock, lib/simplecov-html.rb
`base64` is being used in the gem and so just adding it to the Gemfile is not sufficient. Instead of moving it to the gemspec, just replace it through the equivalent `pack` method call.
=> Drop `base64` dependency, resolve Ruby warning

lib/simplecov-html.rb, views/source_file.erb
In ruby 3.5 most of the functionality will require adding cgi as a dependency.
Only escape/unescape functions will remain, which is all that's needed here. `cgi/escape` is available since Ruby 2.3 with `CGI.escapeHTML`
https://bugs.ruby-lang.org/issues/21258.
=> Only require what is needed from `cgi` for Ruby 3.5 compatibility
